# Set the prefix from C-b to C-a​
set -g prefix C-a
unbind C-b

# Set the delay between prefix and command​
set -s escape-time 1

bind r \
    source-file ~/.config/tmux/tmux.conf \; \
    display-message "Configuration reloaded"​

# Ensure that we can send Ctrl-A to other apps​, simply by pressing Ctrl-a twice. 
bind C-a send-prefix

# Split panes with | and -​
bind | split-window -h
bind - split-window -v

# Move between panes with Prefix h,j,k,l​
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g mouse on

# Get colors used with
#
# for i in {0..255}; do
#     printf '\x1b[38;5;%dmcolour%d\x1b[0m\n' $i $i
# done


# Set the default terminal mode to 256color mode​
# set -g default-terminal "tmux-256colors"

# Set the status line's colors​
set -g status-style fg=white

# Set the color of the window list​
set -g window-status-style fg=cyan,bg=black

# Set colors for the active window​
set -g window-status-current-style fg=colour11,bold

# Colors for pane borders​
set -w -g pane-border-style fg=white
set -w -g pane-active-border-style fg=colour11

# Pane border style: single, double, heavy, simple, number.​
set -w -g pane-border-lines simple

# Add indicators for two-pane setup​
set -g pane-border-indicators arrows

# Add status to panes​
set -g pane-border-status top

# Active pane normal, other shaded out​
# set -g window-style fg=color240,bg=color235
# set -g window-active-style fg=white,bg=black

set -g message-style fg=colour11

# Enable activity alerts​
set -w -g monitor-activity on
set -w -g visual-activity on