#!/usr/bin/env bash
#
# Fan out the canonical AI-tool config (~/.config/ai) to each tool.
#
#   rules/   -> symlinked into Claude + OpenCode, concatenated into Gemini
#   agents/  -> symlinked into Claude; frontmatter-transformed into OpenCode
#   skills/  -> symlinked into Claude
#
# Single source of truth is ~/.config/ai. Edit there, then run this script.
# Safe to re-run; it is idempotent.

set -euo pipefail

AI_HOME="$HOME/.config/ai"
CLAUDE="$HOME/.claude"
OPENCODE="$HOME/.config/opencode"
GEMINI="$HOME/.gemini"

# Agents that should also be published to OpenCode (subset of canonical).
OPENCODE_AGENTS=(
  architect code-architect code-explorer code-reviewer code-simplifier
  database-reviewer doc-updater go-reviewer python-reviewer
  planner comment-analyzer pr-test-analyzer
)

log() { printf '  %s\n' "$*"; }

# link <target> <canonical-source>
# Replace <target> with a symlink to <source>. Real dirs/files are backed up
# once to <target>.bak.<timestamp>; existing symlinks are simply re-pointed.
link() {
  local target="$1" source="$2"
  if [ -L "$target" ]; then
    rm "$target"
  elif [ -e "$target" ]; then
    local bak="${target}.bak.$(date +%Y%m%d%H%M%S)"
    mv "$target" "$bak"
    log "backed up existing $target -> $bak"
  fi
  mkdir -p "$(dirname "$target")"
  ln -s "$source" "$target"
  log "linked $target -> $source"
}

echo "Syncing rules..."
link "$CLAUDE/rules" "$AI_HOME/rules"
link "$OPENCODE/rules" "$AI_HOME/rules"

echo "Syncing skills..."
link "$CLAUDE/skills" "$AI_HOME/skills"

echo "Syncing agents (Claude: symlink)..."
link "$CLAUDE/agents" "$AI_HOME/agents"

echo "Syncing agents (OpenCode: generated frontmatter)..."
mkdir -p "$OPENCODE/agents"
for name in "${OPENCODE_AGENTS[@]}"; do
  src="$AI_HOME/agents/$name.md"
  [ -f "$src" ] || { log "skip $name (not in canonical)"; continue; }
  desc=$(awk -F': ' '/^description:/{sub(/^description: /,"");print;exit}' "$src")
  {
    echo "---"
    echo "name: $name"
    echo "description: $desc"
    echo "mode: subagent"
    echo "---"
    awk 'BEGIN{c=0} /^---$/{c++;next} c>=2{print}' "$src"
  } > "$OPENCODE/agents/$name.md"
done
log "wrote ${#OPENCODE_AGENTS[@]} OpenCode agents"

echo "Syncing instructions (Gemini: concatenated GEMINI.md)..."
mkdir -p "$GEMINI"
{
  echo "# Global instructions"
  echo
  echo "<!-- Generated by ~/.config/ai/sync.sh. Edit ~/.config/ai/rules instead. -->"
  echo
  for f in "$AI_HOME"/rules/common/*.md; do
    [ -f "$f" ] || continue
    cat "$f"
    echo
  done
} > "$GEMINI/GEMINI.md"
log "wrote $GEMINI/GEMINI.md"

echo "Done."
